sudo: required
language: node_js
node_js:
- 7.8
services:
- docker
after_success:
- |-
  if [ ! -z "$TRAVIS_TAG" ]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASS;
    docker build -t $DOCKERHUB_REPO:$COMMIT_HASH .
    docker tag $DOCKERHUB_REPO:$COMMIT_HASH $DOCKERHUB_REPO:$TRAVIS_TAG;
  fi
notifications:
  slack:
    rooms:
    - ssense:NaXRxZ0oVCeDOrhnc6YUAltp#wms-ci
    - ssense:NaXRxZ0oVCeDOrhnc6YUAltp#build
    template:
    - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_message}"
    - 'Build: <%{build_url}|#%{build_number}>'
    - 'Compare: <%{compare_url}|%{commit}>'
    - 'Duration: %{duration} - Elapsed time: %{elapsed_time}'
    - 'Result: %{result}: %{message}'
env:
  global:
  - COMMIT_HASH=${TRAVIS_COMMIT::8}
  - DOCKERHUB_REPO="ssense/$(basename $TRAVIS_REPO_SLUG)"
